name: Node.js Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: |
          cd frontend/react-frontend
          npm install
      - run: |
          cd frontend/react-frontend
          npm i
      - name: Run build
        run: |
          cd frontend/react-frontend
          npm run build          

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: |
          cd frontend/react-frontend
          npm install
      - run: |
          cd frontend/react-frontend
          npm i
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
